# Generated by Django 3.0.6 on 2020-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuliner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('desc', models.TextField(default='')),
                ('alamat', models.TextField(default='')),
                ('jam_buka', models.CharField(default='', max_length=5)),
                ('jam_tutup', models.CharField(default='', max_length=5)),
                ('harga', models.CharField(default='', max_length=11)),
                ('images', models.ImageField(upload_to='', verbose_name='images/')),
            ],
        ),
    ]
