# Generated by Django 3.0.6 on 2020-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pariwisataapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pariwisata',
            name='pariwisata_code',
        ),
        migrations.AddField(
            model_name='pariwisata',
            name='alamat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pariwisata',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pariwisata',
            name='harga',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='pariwisata',
            name='jam_buka',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='pariwisata',
            name='jam_tutup',
            field=models.CharField(default='', max_length=5),
        ),
    ]
