# Generated by Django 3.0.6 on 2020-07-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pariwisataapi', '0003_pariwisata_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pariwisata',
            name='images',
        ),
    ]
